"""glTF/GLB export for the Three.js inspection client."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

import numpy as np
import trimesh
from trimesh.visual import TextureVisuals
from trimesh.visual.material import PBRMaterial

from home_design.errors import ExportError
from home_design.capabilities import ComponentRegistry
from home_design.member_assemblies import MemberAssemblies
from home_design.json_types import JsonObject, JsonValue
from home_design.resolved import MeshData, ResolvedElement, ResolvedModel
from home_design.view_navigation import ViewLink, ViewNavigation
from home_design.view_properties import ViewProperties


class GltfExporter:
    """Export resolved meshes with stable, selectable node names."""

    def export(
        self, model: ResolvedModel, glb_path: Path, manifest_path: Path
    ) -> JsonObject:
        """Write a binary glTF scene and its element manifest.

        :param model: Adapter-neutral resolved model.
        :param glb_path: Destination GLB path.
        :param manifest_path: Destination JSON manifest path.
        :returns: Manifest mapping.
        :raises ExportError: If serialization fails.
        """
        scene = trimesh.Scene(base_frame="home-design-root")
        materials = self._materials(model.materials)
        element_entries: dict[str, JsonValue] = {}
        links = list(ViewNavigation(model).build())
        for element in model.elements:
            node_names: list[JsonValue] = []
            children = (
                MemberAssemblies.children(element)
                if element.kind in MemberAssemblies.CHILD_KINDS
                else ()
            )
            mesh_children = {
                id(mesh): child for child in children for mesh in child.meshes
            }
            child_nodes: dict[str, list[JsonValue]] = {
                child.element_id: [] for child in children
            }
            visible_meshes = [mesh for mesh in element.meshes if mesh.role != "void"]
            for index, mesh_data in enumerate(visible_meshes):
                child = mesh_children.get(id(mesh_data))
                node_name = self._node_name(
                    child.element_id if child is not None else element.element_id,
                    0 if child is not None else index,
                    1 if child is not None else len(visible_meshes),
                )
                mesh = self._mesh(mesh_data, materials)
                mesh.metadata = {
                    "homeDesignId": (
                        child.element_id if child is not None else element.element_id
                    ),
                    "kind": element.kind,
                    "role": mesh_data.role,
                }
                transform = np.eye(4, dtype=np.float64)
                origin = np.asarray(mesh.bounds, dtype=np.float64).mean(axis=0)
                mesh.apply_translation(-origin)
                transform[:3, 3] = origin
                scene.add_geometry(
                    mesh,
                    node_name=node_name,
                    geom_name=node_name,
                    transform=transform,
                )
                node_names.append(node_name)
                if child is not None:
                    child_nodes[child.element_id].append(node_name)
            entry = self._entry(element, node_names)
            entry["children"] = [child.element_id for child in children]
            element_entries[element.element_id] = entry
            for child in children:
                child_entry = self._entry(child, child_nodes[child.element_id])
                child_entry.update(
                    {
                        "parentId": element.element_id,
                        "storeyId": element.storey_id,
                        "defaultVisible": entry["defaultVisible"],
                    }
                )
                element_entries[child.element_id] = child_entry
                links.append(
                    ViewLink(
                        child.element_id,
                        element.element_id,
                        "generated",
                        "Generated by",
                        "Generated member",
                    )
                )
        manifest: JsonObject = {
            "format": "home-design-render-manifest-0.1",
            "modelVersion": model.model_version,
            "sourceRevision": model.source_revision,
            "project": {
                "id": model.project.get("id"),
                "name": model.project.get("name"),
            },
            "coordinateTransform": {
                "source": "right-handed Z-up millimetres",
                "target": "right-handed Y-up metres",
                "mapping": ["x/1000", "z/1000", "-y/1000"],
            },
            "elements": element_entries,
            "navigation": {
                "format": "home-design-navigation-0.1",
                "links": [link.to_dict() for link in links],
            },
            "propertyFormat": "home-design-view-properties-0.1",
            "storeys": {identity: value for identity, value in model.levels.items()},
            "requirements": list(model.requirements),
            "requirementResults": list(model.requirement_results),
            "solarStudies": list(model.solar_studies),
            "reports": {
                "schedules": "schedules.json",
                "envelope": "envelope.json",
                "drawings": "drawings.svg",
            },
        }
        try:
            glb_path.parent.mkdir(parents=True, exist_ok=True)
            manifest_path.parent.mkdir(parents=True, exist_ok=True)
            exported = scene.export(file_type="glb")
            if not isinstance(exported, bytes):
                raise ExportError("Trimesh did not return a binary GLB payload")
            glb_path.write_bytes(exported)
            manifest_path.write_text(
                json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
            )
        except (OSError, ValueError) as error:
            raise ExportError(f"Cannot export GLB scene: {error}") from error
        return manifest

    @staticmethod
    def _entry(element: ResolvedElement, nodes: list[JsonValue]) -> JsonObject:
        """Expose dimensions and labels independently of the full technical property payload."""
        capability = ComponentRegistry.get(element.kind)
        return {
            "kind": element.kind,
            "kindLabel": capability.label,
            "name": (
                ViewProperties.label(
                    str(
                        element.data.get(
                            "constructionRole", element.data.get("role", "member")
                        )
                    )
                )
                if "generatedFrom" in element.data
                else element.name
            ),
            "storeyId": element.storey_id,
            "nodes": nodes,
            "defaultVisible": capability.default_visible,
            "properties": ViewProperties.describe(element.data),
            "data": element.data,
        }

    @staticmethod
    def _mesh(
        mesh_data: MeshData, materials: dict[str, PBRMaterial]
    ) -> trimesh.Trimesh:
        vertices = np.array(
            [(x / 1000.0, z / 1000.0, -y / 1000.0) for x, y, z in mesh_data.vertices],
            dtype=np.float64,
        )
        faces = np.array(mesh_data.faces, dtype=np.int64)
        mesh = trimesh.Trimesh(
            vertices=vertices, faces=faces, process=False, validate=False
        )
        material = materials.get(mesh_data.material_id or "")
        if mesh_data.role == "coordination":
            material = PBRMaterial(
                name="Coordination volume",
                baseColorFactor=[155, 95, 230, 45],
                roughnessFactor=1.0,
                alphaMode="BLEND",
                doubleSided=True,
            )
        elif mesh_data.role == "space":
            material = PBRMaterial(
                name="Space", baseColorFactor=[90, 170, 210, 35], roughnessFactor=1.0
            )
        elif mesh_data.role in {"window-glass", "door-glass"}:
            material = PBRMaterial(
                name="Glass",
                baseColorFactor=[135, 205, 225, 90],
                metallicFactor=0.05,
                roughnessFactor=0.15,
                alphaMode="BLEND",
            )
        if material is not None:
            mesh.visual = TextureVisuals(material=material)
        return mesh

    @staticmethod
    def _materials(materials: JsonObject) -> dict[str, PBRMaterial]:
        result: dict[str, PBRMaterial] = {}
        for material_id, value in materials.items():
            if not isinstance(value, dict):
                continue
            appearance = value.get("appearance")
            appearance = appearance if isinstance(appearance, dict) else {}
            color = str(appearance.get("color", "#B8B4AC"))
            opacity_value = appearance.get("opacity", 1.0)
            opacity = (
                float(opacity_value) if isinstance(opacity_value, (int, float)) else 1.0
            )
            roughness_value = appearance.get("roughness", 0.8)
            roughness = (
                float(roughness_value)
                if isinstance(roughness_value, (int, float))
                else 0.8
            )
            metalness_value = appearance.get("metalness", 0.0)
            metalness = (
                float(metalness_value)
                if isinstance(metalness_value, (int, float))
                else 0.0
            )
            rgba = [int(color[index : index + 2], 16) for index in (1, 3, 5)] + [
                round(opacity * 255)
            ]
            result[material_id] = PBRMaterial(
                name=str(value.get("name", material_id)),
                baseColorFactor=rgba,
                roughnessFactor=roughness,
                metallicFactor=metalness,
                alphaMode="BLEND" if opacity < 1 else "OPAQUE",
            )
        return result

    @staticmethod
    def _node_name(element_id: str, index: int, count: int) -> str:
        slug = re.sub(r"[^A-Za-z0-9_-]+", "_", element_id).strip("_")
        digest = hashlib.sha1(
            element_id.encode("utf-8"), usedforsecurity=False
        ).hexdigest()[:8]
        base = f"hd_{slug}_{digest}"
        return base if count == 1 else f"{base}_part{index + 1}"
